CREATE TABLE USERS(
ID INTEGER IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(15) NOT NULL,
DNI VARCHAR(15) NOT NULL,
DNI_TYPE INTEGER NOT NULL,
POSITION VARCHAR(15) NOT NULL,
AREA INTEGER
)

CREATE TABLE AREAS(
ID INTEGER PRIMARY KEY IDENTITY(1,1) NOT NULL,
AREA VARCHAR(15) NOT NULL
)


CREATE PROCEDURE SPADDUSER(
@NAME VARCHAR(15),
@DNI VARCHAR(15),
@DNI_TYPE INTEGER,
@POSITION VARCHAR(15)
)
AS
BEGIN
INSERT INTO USERS  ( NAME, DNI, DNI_TYPE, POSITION) VALUES(@NAME, @DNI, @DNI_TYPE, @POSITION)
END

CREATE PROCEDURE SPUPDATEUSER(
@NAME VARCHAR(15),
@DNI VARCHAR(15),
@DNI_TYPE INTEGER,
@POSITION VARCHAR(15),
@AREA VARCHAR(15)
)
AS
BEGIN
UPDATE dbo.USERS SET dbo.USERS.NAME = @NAME, DNI = @DNI, DNI_TYPE = @DNI_TYPE, POSITION = @POSITION WHERE @DNI = USERS.DNI AND @DNI_TYPE = USERS.DNI_TYPE
END

CREATE PROCEDURE SPGETUSERS
AS
BEGIN
SELECT * FROM USERS WITH(NOLOCK)
END

